project:
  type: website

website:
  title: "Code of Nature"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Blog"
        href: blog/index.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



